export const COLLAPSE_NAV_MENU = 'COLLAPSE_NAV_MENU';
export const EXPAND_NAV_MENU = 'EXPAND_NAV_MENU';
export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU';

export const EXPAND_MENU = 'EXPAND_MENU';
export const COLLAPSE_MENU = 'COLLAPSE_MENU';

export const UPDATE_ACTIVATED_MENU = 'UPDATE_ACTIVATED_MENU';
export const REFRESH_ACTIVATED_MENU = 'REFRESH_ACTIVATED_MENU';