export const UPDATE_ANALGESIA_DATA_FIELD = 'UPDATE_ANALGESIA_DATA_FIELD';

export const GET_ANALGESIA_DATA_REQUEST = 'GET_ANALGESIA_DATA_REQUEST';
export const GET_ANALGESIA_DATA_SUCCESS = 'GET_ANALGESIA_DATA_SUCCESS';
export const GET_ANALGESIA_DATA_FAILURE = 'GET_ANALGESIA_DATA_FAILURE';

export const UPDATE_ANALGESIA_DATA_REQUEST = 'UPDATE_ANALGESIA_DATA_REQUEST';
export const UPDATE_ANALGESIA_DATA_SUCCESS = 'UPDATE_ANALGESIA_DATA_SUCCESS';
export const UPDATE_ANALGESIA_DATA_FAILURE = 'UPDATE_ANALGESIA_DATA_FAILURE';