export const UPDATE_OBSERVAL_DATA_FIELD = 'UPDATE_OBSERVAL_DATA_FIELD';

export const GET_OBSERVAL_REQUEST = 'GET_OBSERVAL_REQUEST';
export const GET_OBSERVAL_SUCCESS = 'GET_OBSERVAL_SUCCESS';
export const GET_OBSERVAL_FAILURE = 'GET_OBSERVAL_FAILURE';

export const UPDATE_OBSERVAL_DATA_REQUEST = 'UPDATE_OBSERVAL_DATA_REQUEST';
export const UPDATE_OBSERVAL_DATA_SUCCESS = 'UPDATE_OBSERVAL_DATA_SUCCESS';
export const UPDATE_OBSERVAL_DATA_FAILURE = 'UPDATE_OBSERVAL_DATA_FAILURE';