export const UPDATE_OBSERVAL_DATA_FIELD = 'UPDATE_OBSERVAL_DATA_FIELD';

export const UPDATE_OBSERVAL_DATA_REQUEST = 'UPDATE_OBSERVAL_DATA_REQUEST';
export const UPDATE_OBSERVAL_DATA_SUCCESS = 'UPDATE_OBSERVAL_DATA_SUCCESS';
export const UPDATE_OBSERVAL_DATA_FAILURE = 'UPDATE_OBSERVAL_DATA_FAILURE';