export const PATIENT_STEP_PREV = 'PATIENT_STEP_PREV';
export const PATIENT_STEP_NEXT = 'PATIENT_STEP_NEXT';
export const PATIENT_STEP_UPDATE = 'PATIENT_STEP_UPDATE';

export const RESET_PATIENT_DATA = 'RESET_PATIENT_DATA';

export const ENABLE_PATIENT_REQUEST = 'ENABLE_PATIENT_REQUEST';
export const ENABLE_PATIENT_SUCCESS = 'ENABLE_PATIENT_SUCCESS';
export const ENABLE_PATIENT_FAILURE = 'ENABLE_PATIENT_FAILURE';

export const DISABLE_PATIENT_REQUEST = 'DISABLE_PATIENT_REQUEST';
export const DISABLE_PATIENT_SUCCESS = 'DISABLE_PATIENT_SUCCESS';
export const DISABLE_PATIENT_FAILURE = 'DISABLE_PATIENT_FAILURE';