export const UPDATE_PATIENT_INFORMATION_FIELD = 'UPDATE_PATIENT_INFORMATION_FIELD';

export const UPDATE_PATIENT_INFORMATION_REQUEST = 'UPDATE_PATIENT_INFORMATION_REQUEST';
export const UPDATE_PATIENT_INFORMATION_SUCCESS = 'UPDATE_PATIENT_INFORMATION_SUCCESS';
export const UPDATE_PATIENT_INFORMATION_FAILURE = 'UPDATE_PATIENT_INFORMATION_FAILURE';