export const UPDATE_PATIENT_INFORMATION_FIELD = 'UPDATE_PATIENT_INFORMATION_FIELD';

export const GET_PATIENT_INFO_REQUEST = 'GET_PATIENT_INFO_REQUEST';
export const GET_PATIENT_INFO_SUCCESS = 'GET_PATIENT_INFO_SUCCESS';
export const GET_PATIENT_INFO_FAILURE = 'GET_PATIENT_INFO_FAILURE';

export const UPDATE_PATIENT_INFORMATION_REQUEST = 'UPDATE_PATIENT_INFORMATION_REQUEST';
export const UPDATE_PATIENT_INFORMATION_SUCCESS = 'UPDATE_PATIENT_INFORMATION_SUCCESS';
export const UPDATE_PATIENT_INFORMATION_FAILURE = 'UPDATE_PATIENT_INFORMATION_FAILURE';