export const ADD_PATIENT_STEP_PREV = 'ADD_PATIENT_STEP_PREV';
export const ADD_PATIENT_STEP_NEXT = 'ADD_PATIENT_STEP_NEXT';
export const ADD_PATIENT_STEP_UPDATE = 'ADD_PATIENT_STEP_UPDATE';

export const UPDATE_PATIENT_INFORMATION_REQUEST = 'UPDATE_PATIENT_INFORMATION_REQUEST';
export const UPDATE_PATIENT_INFORMATION_SUCCESS = 'UPDATE_PATIENT_INFORMATION_SUCCESS';
export const UPDATE_PATIENT_INFORMATION_FAILURE = 'UPDATE_PATIENT_INFORMATION_FAILURE';