export const ADD_PATIENT_STEP_PREV = 'ADD_PATIENT_STEP_PREV';
export const ADD_PATIENT_STEP_NEXT = 'ADD_PATIENT_STEP_NEXT';
export const ADD_PATIENT_STEP_UPDATE = 'ADD_PATIENT_STEP_UPDATE';

export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE';