export const ADD_PATIENT_STEP_PREV = 'ADD_PATIENT_STEP_PREV';
export const ADD_PATIENT_STEP_NEXT = 'ADD_PATIENT_STEP_NEXT';
export const ADD_PATIENT_STEP_UPDATE = 'ADD_PATIENT_STEP_UPDATE';

export const CREATE_PATIENT_INFORMATION_REQUEST = 'CREATE_PATIENT_INFORMATION_REQUEST';
export const CREATE_PATIENT_INFORMATION_SUCCESS = 'CREATE_PATIENT_INFORMATION_SUCCESS';
export const CREATE_PATIENT_INFORMATION_FAILURE = 'CREATE_PATIENT_INFORMATION_FAILURE';