export const GET_PATIENT_LIST_REQUEST = 'GET_PATIENT_LIST_REQUEST';
export const GET_PATIENT_LIST_SUCCESS = 'GET_PATIENT_LIST_SUCCESS';
export const GET_PATIENT_LIST_FAILURE = 'GET_PATIENT_LIST_FAILURE';